title: Elena Ziege
description: "Elena Ziege | Family and Education Economist | Federal Institute for Population Reesearch (BiB)"
author: "Elena Ziege"
mail: "elena.ziege @ bib.bund.de"
phone : "+49 (0) 611 75 4120"
address1 : "Friedrich-Ebert-Allee 4"
address2 : "65185 Wiesbaden"
google_analytics: G-FJ6V23RWVP

theme: minima

base_url: /

# Minima social links
linkedin_username: elena-ziege

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"
  include_custom_head: true
  
# Minima: custom header links
header_pages:
  - _pages/research.md
  - _pages/policy.md
  - _pages/cv.md

include:
    - _pages
    - _includes/head-custom.html

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag





