title: Elena Ziege
description: 
author: "Elena Ziege"
mail: "elena.ziege@bib.bund.de"

theme: minima

base_url: /

# Minima social links
twitter_username: Elena_Ziege
github_username: eziege
linkedin_username: elena-ziege

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/research.md
  - _pages/policy.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

plugins:
  - jekyll-sitemap
